### ISSUE TITLE
How to use in neovim?

### ISSUE THREAD

**Issue by Muizzyranking** [xlittlerag/tree-sitter-clarity#2]
This is not a bug and I don't know where else to ask, how can I use this in neovim? I've followed treesitter nvim guide on adding new parser but I still don't get syntax highlighting.

**Comment by xlittlerag** [comment]
Hi, you need to copy the highlights queries to nvim-treesitter directory. For lazy, I run:

```bash
mkdir ~/.local/share/nvim/lazy/nvim-treesitter/queries/clarity
cp ./queries/highlights.scm ~/.local/share/nvim/lazy/nvim-treesitter/queries/clarity/
```

This is the way I've found. The nvim-treesitter plugin has all the queries for the other languages in its repo. I don't know if there is a cleaner way to do it.

**Comment by Muizzyranking** [comment]
Oh, thank you so much. I moved it `~/.config/nvim/queries/clarity/highlights.scm` to keep all my config in one place and it worked. Thank you very much.
